name: Migrate Database

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm install
      - name: Run Migrations
        run: npx sequelize-cli db:migrate
