export const mobileProducts = [
  'iPhone 16',
  'Samsung Galaxy S25',
  'OnePlus 13',
  'Nothing Phone 3',
  'Realme GT 7',
  'Xiaomi 15',
  'Google Pixel 10',
  'Vivo X300',
  'Oppo Find X9',
  'Motorola Edge 70',
];

export const laptopProducts = [
  'MacBook Air M4',
  'Dell Inspiron 15',
  'HP Pavilion',
  'Lenovo IdeaPad',
  'Asus VivoBook',
  'Acer Aspire 7',
  'MSI Modern 15',
  'LG Gram',
  'Dell XPS 13',
  'HP Victus',
];

export const tabletProducts = [
  'iPad Air',
  'Samsung Galaxy Tab',
  'Lenovo Tab',
  'Xiaomi Pad',
  'OnePlus Pad',
  'Realme Pad',
  'Honor Pad',
  'Nokia Tablet',
  'Huawei MatePad',
  'Amazon Fire Tablet',
];

export const smartWatchProducts = [
  'Apple Watch',
  'Galaxy Watch',
  'Noise Smart Watch',
  'Fire-Boltt Ninja',
  'Boat Wave',
  'Fastrack Smart Watch',
  'Realme Watch',
  'OnePlus Watch',
  'Titan Smart Watch',
  'Amazfit Watch',
];

export const headphoneProducts = [
  'Boat Rockerz 550',
  'JBL Tune 760',
  'Sony WH-1000XM5',
  'Noise Air Buds',
  'Realme Buds Air',
  'OnePlus Buds Pro',
  'Samsung Galaxy Buds',
  'Apple AirPods Pro',
  'Boult Audio X1',
  'Skullcandy Hesh',
];

export const cameraProducts = [
  'Canon EOS 1500D',
  'Canon EOS R50',
  'Nikon D7500',
  'Sony Alpha A6400',
  'Fujifilm X-T5',
  'GoPro Hero 13',
  'DJI Pocket 3',
  'Panasonic Lumix',
  'Nikon Z6 II',
  'Canon PowerShot',
];

export const bookProducts = [
  'Clean Code',
  'Java Programming',
  'Angular for Beginners',
  'Node.js Complete Guide',
  'LoopBack 4 Handbook',
  'AWS Cloud Basics',
  'Python Programming',
  'Data Structures',
  'The Alchemist',
  'Atomic Habits',
];

export const beautyProducts = [
  'Lakme Face Wash',
  'Mamaearth Shampoo',
  'Himalaya Face Cream',
  'Nivea Body Lotion',
  'Dove Soap',
  'Maybelline Lipstick',
  'LOréal Hair Serum',
  'Ponds Face Cream',
  'Garnier Face Wash',
  'Lakme Kajal',
];

export const sportsProducts = [
  'Cricket Bat',
  'Football',
  'Badminton Racket',
  'Basketball',
  'Yoga Mat',
  'Skipping Rope',
  'Gym Gloves',
  'Dumbbell Set',
  'Tennis Ball',
  'Sports Shoes',
];

export const furnitureProducts = [
  'Office Chair',
  'Study Table',
  'Wooden Bed',
  'Sofa Set',
  'Dining Table',
  'Bookshelf',
  'TV Unit',
  'Coffee Table',
  'Wardrobe',
  'Computer Desk',
];

export const homeApplianceProducts = [
  'Refrigerator',
  'Washing Machine',
  'Microwave Oven',
  'Air Conditioner',
  'Water Purifier',
  'Ceiling Fan',
  'Mixer Grinder',
  'Vacuum Cleaner',
  'Electric Kettle',
  'Air Fryer',
];

export const kitchenApplianceProducts = [
  'Mixer Grinder',
  'Induction Cooktop',
  'Rice Cooker',
  'Toaster',
  'Sandwich Maker',
  'Juicer',
  'Blender',
  'Electric Kettle',
  'Coffee Maker',
  'Air Fryer',
];
export const groceryProducts = [
  'Basmati Rice',
  'Wheat Flour',
  'Cooking Oil',
  'Sugar',
  'Tea Powder',
  'Coffee',
  'Salt',
  'Milk',
  'Biscuits',
  'Fruit Juice',
];

export const televisionProducts = [
  'Samsung 55 Inch Smart TV',
  'LG OLED TV',
  'Sony Bravia 4K TV',
  'Mi Smart TV',
  'OnePlus QLED TV',
  'TCL Android TV',
  'Vu Premium TV',
  'Panasonic LED TV',
  'Hisense Smart TV',
  'Realme Smart TV',
];
export const gamingProducts = [
  'PlayStation 5',
  'Xbox Series X',
  'Nintendo Switch',
  'Gaming Keyboard',
  'Gaming Mouse',
  'Gaming Chair',
  'Gaming Monitor',
  'Gaming Headset',
  'Gaming Controller',
  'Gaming Desk',
];
export const computerAccessoryProducts = [
  'Wireless Mouse',
  'Mechanical Keyboard',
  'USB Hub',
  'Laptop Stand',
  'External Hard Drive',
  'Webcam',
  'USB Keyboard',
  'Mouse Pad',
  'WiFi Adapter',
  'Laptop Cooling Pad',
];
export const mobileAccessoryProducts = [
  'Mobile Back Cover',
  'Tempered Glass',
  'Fast Charger',
  'USB Type-C Cable',
  'Power Bank',
  'Car Mobile Holder',
  'Selfie Stick',
  'Wireless Charger',
  'Phone Ring Holder',
  'Mobile Tripod',
];
export const menClothingProducts = [
  'Cotton T-Shirt',
  'Casual Shirt',
  'Blue Jeans',
  'Formal Trousers',
  'Hoodie',
  'Polo T-Shirt',
  'Denim Jacket',
  'Track Pants',
  'Kurta',
  'Blazer',
];

export const womenClothingProducts = [
  'Kurti',
  'Saree',
  'Top',
  'Jeans',
  'Leggings',
  'Dress',
  'Palazzo',
  'T-Shirt',
  'Jacket',
  'Sweater',
];
export const kidsClothingProducts = [
  'Kids T-Shirt',
  'Kids Jeans',
  'Kids Frock',
  'School Uniform',
  'Kids Hoodie',
  'Kids Shorts',
  'Kids Jacket',
  'Kids Night Suit',
  'Baby Romper',
  'Kids Track Suit',
];
export const footwearProducts = [
  'Running Shoes',
  'Casual Shoes',
  'Sports Shoes',
  'Sneakers',
  'Sandals',
  'Formal Shoes',
  'Slippers',
  'Loafers',
  'Boots',
  'Flip Flops',
];
export const bagProducts = [
  'Laptop Bag',
  'School Bag',
  'Travel Backpack',
  'Handbag',
  'Office Bag',
  'Gym Bag',
  'Duffel Bag',
  'Wallet',
  'Sling Bag',
  'Trolley Bag',
];
export const jewelleryProducts = [
  'Gold Necklace',
  'Silver Ring',
  'Diamond Earrings',
  'Bracelet',
  'Pendant',
  'Bangles',
  'Anklet',
  'Chain',
  'Stud Earrings',
  'Pearl Necklace',
];

export const watchProducts = [
  'Titan Watch',
  'Fastrack Watch',
  'Casio Watch',
  'Rolex Watch',
  'Citizen Watch',
  'Timex Watch',
  'Sonata Watch',
  'Fossil Watch',
  'Smart Analog Watch',
  'Sports Watch',
];
export const personalCareProducts = [
  'Face Wash',
  'Body Wash',
  'Shampoo',
  'Conditioner',
  'Hair Oil',
  'Body Lotion',
  'Hand Wash',
  'Toothpaste',
  'Toothbrush',
  'Face Scrub',
];
export const perfumeProducts = [
  'Men Perfume',
  'Women Perfume',
  'Body Mist',
  'Deodorant Spray',
  'Roll On',
  'Luxury Perfume',
  'Fresh Fragrance',
  'Woody Perfume',
  'Floral Perfume',
  'Pocket Perfume',
];
export const stationeryProducts = [
  'Notebook',
  'Ball Pen',
  'Gel Pen',
  'Pencil Box',
  'Sketch Book',
  'Highlighter',
  'Marker',
  'Eraser',
  'Sharpener',
  'Drawing Book',
];
export const officeSupplyProducts = [
  'Office Chair',
  'Office Desk',
  'Stapler',
  'Paper Cutter',
  'Printer Paper',
  'File Folder',
  'Desk Organizer',
  'Calculator',
  'Whiteboard',
  'Notice Board',
];

export const cleaningSupplyProducts = [
  'Floor Cleaner',
  'Glass Cleaner',
  'Toilet Cleaner',
  'Cleaning Brush',
  'Mop Set',
  'Dustbin',
  'Cleaning Gloves',
  'Dish Wash Liquid',
  'Surface Cleaner',
  'Microfiber Cloth',
];
export const fruitProducts = [
  'Apple',
  'Banana',
  'Orange',
  'Mango',
  'Potato',
  'Tomato',
  'Onion',
  'Carrot',
  'Cucumber',
  'Capsicum',
];
export const beverageProducts = [
  'Green Tea',
  'Coffee',
  'Fruit Juice',
  'Soft Drink',
  'Energy Drink',
  'Mineral Water',
  'Milk Shake',
  'Cold Coffee',
  'Lemon Juice',
  'Protein Drink',
];
export const snackProducts = [
  'Potato Chips',
  'Nachos',
  'Popcorn',
  'Chocolate',
  'Cookies',
  'Biscuits',
  'Dry Fruits',
  'Salted Peanuts',
  'Instant Noodles',
  'Energy Bar',
];
export const dairyProducts = [
  'Milk',
  'Butter',
  'Cheese',
  'Paneer',
  'Curd',
  'Fresh Cream',
  'Ghee',
  'Yogurt',
  'Flavoured Milk',
  'Ice Cream',
];
export const babyCareProducts = [
  'Baby Diapers',
  'Baby Wipes',
  'Baby Shampoo',
  'Baby Soap',
  'Baby Powder',
  'Baby Lotion',
  'Baby Oil',
  'Baby Feeding Bottle',
  'Baby Blanket',
  'Baby Toy',
];
export const petProducts = [
  'Dog Food',
  'Cat Food',
  'Pet Shampoo',
  'Dog Collar',
  'Pet Bed',
  'Pet Bowl',
  'Bird Cage',
  'Fish Food',
  'Pet Toy',
  'Pet Grooming Kit',
];
export const healthCareProducts = [
  'Digital Thermometer',
  'Blood Pressure Monitor',
  'Pulse Oximeter',
  'First Aid Kit',
  'Vitamin Tablets',
  'Face Mask',
  'Hand Sanitizer',
  'Pain Relief Spray',
  'Medical Gloves',
  'Hot Water Bag',
];
export const fitnessProducts = [
  'Treadmill',
  'Exercise Cycle',
  'Resistance Band',
  'Yoga Block',
  'Foam Roller',
  'Protein Shaker',
  'Pull Up Bar',
  'Ab Roller',
  'Exercise Ball',
  'Kettlebell',
];
export const automotiveProducts = [
  'Car Vacuum Cleaner',
  'Car Cover',
  'Car Air Freshener',
  'Engine Oil',
  'Tyre Inflator',
  'Jump Starter',
  'Car Polish',
  'Car Wash Shampoo',
  'Bike Cover',
  'Helmet',
];
export const bikeAccessoryProducts = [
  'Bike Helmet',
  'Bike Gloves',
  'Bike Cover',
  'Bike Phone Holder',
  'Bike Mirror',
  'Bike Seat Cover',
  'Bike LED Light',
  'Bike Lock',
  'Bike Tool Kit',
  'Bike Bottle Holder',
];
export const carAccessoryProducts = [
  'Car Seat Cover',
  'Car Phone Holder',
  'Car Charger',
  'Car Floor Mat',
  'Car Perfume',
  'Car Dash Camera',
  'Steering Cover',
  'Sunshade',
  'Reverse Camera',
  'Car Cleaning Kit',
];
export const toolProducts = [
  'Hammer',
  'Screwdriver Set',
  'Electric Drill',
  'Measuring Tape',
  'Pliers',
  'Adjustable Wrench',
  'Tool Box',
  'Allen Key Set',
  'Saw',
  'Wire Cutter',
];
export const gardenProducts = [
  'Flower Pot',
  'Watering Can',
  'Garden Hose',
  'Garden Shovel',
  'Grass Cutter',
  'Plant Seeds',
  'Garden Gloves',
  'Fertilizer',
  'Plant Stand',
  'Pruning Shears',
];
export const toyProducts = [
  'Remote Control Car',
  'Building Blocks',
  'Puzzle Game',
  'Teddy Bear',
  'Toy Train',
  'Doll House',
  'Action Figure',
  'Toy Kitchen Set',
  'Board Game',
  'Toy Helicopter',
];
export const musicalInstrumentProducts = [
  'Acoustic Guitar',
  'Electric Guitar',
  'Keyboard Piano',
  'Drum Set',
  'Violin',
  'Flute',
  'Ukulele',
  'Microphone',
  'Tabla',
  'Harmonica',
];
export const giftProducts = [
  'Greeting Card',
  'Photo Frame',
  'Coffee Mug',
  'Gift Hamper',
  'Soft Toy',
  'LED Lamp',
  'Key Chain',
  'Chocolate Box',
  'Personalized Bottle',
  'Desk Clock',
];
export const travelAccessoryProducts = [
  'Travel Backpack',
  'Neck Pillow',
  'Passport Cover',
  'Travel Bottle',
  'Luggage Bag',
  'Travel Organizer',
  'Power Bank',
  'Travel Adapter',
  'Sleeping Mask',
  'Luggage Lock',
];
export const smartHomeProducts = [
  'Smart Bulb',
  'Smart Plug',
  'Smart Door Lock',
  'Smart Camera',
  'Smart Speaker',
  'Smart Door Bell',
  'Robot Vacuum',
  'Smart Switch',
  'Smart Sensor',
  'Smart Curtain Controller',
];
export const lightingProducts = [
  'LED Bulb',
  'Tube Light',
  'Ceiling Light',
  'Wall Light',
  'Night Lamp',
  'Study Lamp',
  'Pendant Light',
  'Floor Lamp',
  'LED Strip Light',
  'Emergency Light',
];
export const storageProducts = [
  'Storage Box',
  'Plastic Container',
  'Wardrobe Organizer',
  'Shoe Rack',
  'Kitchen Storage Jar',
  'Drawer Organizer',
  'Laundry Basket',
  'Storage Cabinet',
  'Bookshelf Organizer',
  'Clothes Organizer',
];