export const productImageMap: {[key: string]: string} = {
  'iPhone 16': '/images/products/mobiles/iphone16.jpg',
  'Samsung Galaxy S25': '/images/products/mobiles/samsung-galaxy-s25.jpg',
  'OnePlus 13': '/images/products/mobiles/OnePlus13.jpg',
  'Nothing Phone 3': '/images/products/mobiles/nothing-phone3.jpg',
  'Realme GT 7': '/images/products/mobiles/realme-gt7.jpg',
  'Xiaomi 15': '/images/products/mobiles/xiaomi-15-pro.jpg',
  'Google Pixel 10': '/images/products/mobiles/google-pixel10.jpg',
  'Vivo X300': '/images/products/mobiles/vivo-x300.jpg',
  'Oppo Find X9': '/images/products/mobiles/oppo-findx9.jpg',
  'Motorola Edge 70': '/images/products/mobiles/motorola-edge70.jpg',

  'MacBook Air M4': '/images/products/laptops/Apple-MacBook-Air-m3.jpg',
  'Dell Inspiron 15': '/images/products/laptops/dell-inspiron15.jpg',
  'HP Pavilion': '/images/products/laptops/hp-pavilion.jpg',
  'Lenovo IdeaPad': '/images/products/laptops/lenovo-ideapad.jpg',
  'Asus VivoBook': '/images/products/laptops/asus-vivobook.jpg',
  'Acer Aspire 7': '/images/products/laptops/acer-aspire7.jpg',
  'MSI Modern 15': '/images/products/laptops/msi-modern15.jpg',
  'LG Gram': '/images/products/laptops/lg-gram16.jpg',
  'Dell XPS 13': '/images/products/laptops/dell-xps13.jpg',
  'HP Victus': '/images/products/laptops/hp-victus.jpg',

  'iPad Air': '/images/products/tablets/ipad-air.jpg',
  'Samsung Galaxy Tab': '/images/products/tablets/samsung-galaxy-tab.jpg',
  'Lenovo Tab': '/images/products/tablets/lenovo-tab-plus.jpg',
  'Xiaomi Pad': '/images/products/tablets/xiaomi-pad6.jpg',
  'OnePlus Pad': '/images/products/tablets/oneplus-pad2.jpg',
  'Realme Pad': '/images/products/tablets/realme-pad3.jpg',

  'Boat Rockerz 550': '/images/products/headphones/boat-rockerz-plus-550.jpg',
  'JBL Tune 760': '/images/products/headphones/JBL-Tune-760NC.jpg',
  'Sony WH-1000XM5': '/images/products/headphones/WH-1000XM5.jpg',
  'Noise Air Buds': '/images/products/headphones/noice-air-buds-pro.jpg',
  'Realme Buds Air': '/images/products/headphones/realme-buds-air3-RMA2105.jpg',
  'OnePlus Buds Pro': '/images/products/headphones/oneplus-buds-pro3.jpg',
  'Samsung Galaxy Buds':
    '/images/products/headphones/samsung-galaxy-buds-live.jpg',
  'Apple AirPods Pro': '/images/products/headphones/apple-airpod-pro.jpg',
  'Boult Audio X1':
    '/images/products/headphones/boult-audio-probass-x1-air.jpg',
  'Skullcandy Hesh': '/images/products/headphones/skullcandy-hash-evo.jpg',

  'Clean Code': '/images/products/books/clean-code.jpg',
  'Java Programming': '/images/products/books/java.jpg',
  'Angular for Beginners': '/images/products/books/angular.jpg',
  'Node.js Complete Guide': '/images/products/books/nodejs.jpg',
  'AWS Cloud Basics': '/images/products/books/cloud-computing-with-AWS.jpg',
  'Python Programming': '/images/products/books/python.jpg',
  'The Alchemist': '/images/products/books/alchemist.jpg',
  'Atomic Habits': '/images/products/books/atmic-habits.jpg',

  'Cricket Bat': '/images/products/sports/cricket-bat.jpg',
  'Football': '/images/products/sports/football.jpg',
  'Badminton Racket': '/images/products/sports/badminton-racket.jpg',
  'Basketball': '/images/products/sports/basketball.jpg',
  'Yoga Mat': '/images/products/sports/yoga-mat.jpg',
  'Skipping Rope': '/images/products/sports/skipping-rope.jpg',
  'Gym Gloves': '/images/products/sports/gym-gloves.jpg',
  'Dumbbell Set': '/images/products/sports/dumbbell-set.jpg',
  'Tennis Ball': '/images/products/sports/tennisball.jpg',
  'Sports Shoes': '/images/products/sports/sports-shoes.jpg',

  'Office Chair': '/images/products/furnitures/office-chair.jpg',
  'Study Table': '/images/products/furnitures/study-table.jpg',
  'Wooden Bed': '/images/products/furnitures/wooden-bed.jpg',
  'Sofa Set': '/images/products/furnitures/sofaset.jpg',
  'Dining Table': '/images/products/furnitures/diningtable.jpg',
  'Bookshelf': '/images/products/furnitures/bookshelf.jpg',
  'TV Unit': '/images/products/furnitures/TVUnit.jpg',
  'Coffee Table': '/images/products/furnitures/coffeetable.jpg',
  'Wardrobe': '/images/products/furnitures/wardrobe.jpg',
  'Computer Desk': '/images/products/furnitures/computerdesk.jpg',

  'Washing Machine': '/images/products/homeAppliances/washing-machine.jpg',
  'Microwave Oven': '/images/products/homeAppliances/microwave-oven.jpg',
  'Air Conditioner': '/images/products/homeAppliances/air-conditioner.jpg',
  'Water Purifier': '/images/products/homeAppliances/water-purifier.jpg',
  'Ceiling Fan': '/images/products/homeAppliances/celling-fan.jpg',
  'Mixer Grinder': '/images/products/homeAppliances/mixer-grinder.jpg',
  'Vacuum Cleaner': '/images/products/homeAppliances/vaccum-cleaner.jpg',

};
