name: BMS CI Pipeline

on:
  push:
    branches:
      - main
      - solid-principle

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bms-typescript

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc